server:
  port: 8081
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
#  url: jdbc:mysql://47.96.170.5:3306/cake?useSSl=false&serverTimezone=GMT%2B8
    ##    username: root
    ##    password: 123456
    url: jdbc:mysql://127.0.1.1:3306/cake?useSSl=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: ${actived:dev}
logging:
  level:
    root: warn
    com.oms.dao: trace
  pattern:
    console: '%p%m%n'

project:
  version: @project.version@
