spring:
  profiles:
    active: ${ENVIRONMENT_TYPE:dev}
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://47.96.170.5:3306/cake?useSSl=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

project:
  version: @project.version@